version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo

jobs:
  build-and-test:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Set Up Maven Dependencies
          command: mvn dependency:go-offline
      - run:
          name: Build and Test
          command: mvn clean package
      - run:
          name: Generate Code Coverage
          command: mvn jacoco:report
      - persist_to_workspace:
          root: ~/repo
          paths:
            - target

  docker-build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/repo
      - run:
          name: Verify Target Directory
          command: ls ~/repo
      - run:
          name: Build Docker Image
          command: docker build --no-cache -t aniket104/systemmonitor:latest ~/repo
      - run:
          name: Push Docker Image to Dockerhub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push aniket104/systemmonitor:latest

workflows:
  version: 2
  test-and-build:
    jobs:
      - build-and-test
      - docker-build:
          requires:
            - build-and-test
