version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo

  docker-executor:
    docker:
      - image: docker:stable
    working_directory: ~/repo

jobs:
  build-and-test:
    executor: maven-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-deps-{{ checksum "pom.xml" }}
            - maven-deps-
      - run:
          name: Set Up Maven Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: maven-deps-{{ checksum "pom.xml" }}
      - run:
          name: Build and Test
          command: mvn clean package
      - run:
          name: Generate Code Coverage
          command: mvn jacoco:report
      - persist_to_workspace:
          root: ~/repo
          paths:
            - target
      - run:
          name: Upload Coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f target/site/jacoco/jacoco.xml
      - store_artifacts:
          path: target/site/jacoco
          destination: jacoco

  docker-build:
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker
      - run:
          name: Verify Presence of Dockerfile and Target Directory
          command: |
            echo "Listing contents of ~/repo:"
            ls -l ~/repo
            echo "Listing contents of ~/repo/target:"
            ls -l ~/repo/target
      - run:
          name: Build Docker Image
          command: |
            cd ~/repo
            docker build --no-cache -t aniket104/systemmonitor:latest .
      - run:
          name: Push Docker Image to Dockerhub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push aniket104/systemmonitor:latest

workflows:
  version: 2
  test-and-build:
    jobs:
      - build-and-test
      - docker-build:
          requires:
            - build-and-test
